# Generated by Django 4.1 on 2022-09-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('comentario', models.CharField(blank=True, max_length=100, verbose_name='Comentario')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('Publicaciones', models.ManyToManyField(to='revista.publicaciones')),
            ],
        ),
    ]
