# Generated by Django 4.1 on 2022-09-17 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0002_autorizaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='titulo')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripcion')),
                ('tipo', models.CharField(choices=[('G', 'Grafica'), ('D', 'Divulgativa'), ('I', 'Informativa'), ('E', 'Educativa')], default='E', max_length=1)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('publicaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista.publicaciones')),
            ],
        ),
    ]
