# Generated by Django 4.1 on 2022-09-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0003_articulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripcion')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('Articulos', models.ManyToManyField(to='revista.articulos')),
            ],
        ),
    ]
